### ISSUE TITLE
视频横屏播放有bug

### ISSUE THREAD

**Issue by DavidWeiZhong** [GeekGhost/Ghost#11]
视频不能够横屏播放，一横屏就会重新开始竖屏播放

**Comment by DavidWeiZhong** [comment]
楼主的VidioInfoActivity没有设置
 android:configChanges="orientation|screenSize|keyboardHidden"
  android:screenOrientation="portrait"

**Comment by dujuejue** [comment]
给力啊，兄弟

**Comment by caopeng000** [comment]
已修复
