### ISSUE TITLE
请问在mvp的view中怎么获取fragment对象呢，比如在view中得到getChildFragmentManager()

### ISSUE THREAD

**Issue by Yis92** [GeekGhost/Ghost#17]
请问在mvp的view中怎么获取fragment对象呢，比如在view中得到getChildFragmentManager()

**Comment by stevenMieMie** [comment]
后来经过考虑这种方式并不适合实际开发，现在自定义view这一块已经摘掉了，还是在activity或fagmeng中作为view处理

**Comment by Yis92** [comment]
谢谢修改，还有一个新的问题，就是在导入阿里的jar的时候发现项目会有冲突，出现 java.lang.VerifyError 的校验错误，能加个qq具体说下吗？767035003
