### ISSUE TITLE
看了下效果，非常棒，关于那个福利的图片显示

### ISSUE THREAD

**Issue by dongjunkun** [GeekGhost/Ghost#3]
看了下效果，非常棒，关于那个福利的图片显示，第一眼居然没有跳跃感，我的gank里面还没解决这个问题，然后好奇看了下你的代码，居然只是随机设置了图片的高度，看来还是没有解决这个问题，因为gank没有提供图片尺寸的字段，目前就看到有一个客户端[RealStuff](https://github.com/IvorHu/RealStuff)解决了这个问题，但也是完全下载图片后计算图片的尺寸，感觉有些慢，iOS里面有个库[ImageScout](https://github.com/kaishin/ImageScout)可以用很小的代价获取远程图片的尺寸，目前android这边我还没找到类似的库

**Comment by stevenMieMie** [comment]
是这样的，gank确实没有提供图片大小的字段，这个高度字段是我自己添加的，我是通过在拿到图片数据后给这个字段设置随机高度，然后在holder中通过高度字段动态设置图片的高度参数。（有不懂的可以随时提问）
实体类：
```

private int height;
public int getHeight() {
     return height;
    }
public void setHeight(int height) {
    this.height = height;
    }
```
holder赋值：
```
ViewGroup.LayoutParams params = imgPicture.getLayoutParams();
params.height = data.getHeight();
imgPicture.setLayoutParams(params);
```

**Comment by dongjunkun** [comment]
这个代码我看到了，主要想说的在后面android这边有没有一种方法可以通过很小的代价获取远程图片尺寸，就像iOS的ImageScout这样的

**Comment by stevenMieMie** [comment]
我目前还没有发现，之前一直都是后台动态裁图的方式。
