### ISSUE TITLE
有几个小问题想请教一下作者.希望作者能解答一下,谢谢.

### ISSUE THREAD

**Issue by JamesLebron** [GeekGhost/Ghost#9]
小弟才疏学浅,在仔细看了代码之后有几个问题实在是想不通,想请教一下.
  1.关于MVP的分层问题. 在细细看了代码之后,发现有些代码和我之前看的T-MVP 非常像,T-MVP是在Presenter 里面有个RxManager,在Presenter onDestory 的时候,统一取消Observable.你的项目是在RxPresenter 里面做的,反正原理都一模一样,就是统一unsubscribe 所有的Observable.  T-MVP的层次结构是标准的三层,有标准的契约类,activity ,fragment是作为View 层,有专门的Model层,有专门的Presenter,但是你的项目是把所有的布局文件inflate 到一个View 上面,然后把这个View承载在activity 或者fragment上面,然后没有专门提供Model,是直接在Presenter 里面做的API 调用操作... (我看过市面上很多项目也这样把,直接把model 层的API 调用操作放到Presenter里面).我想问,这样的分层有好处呢?然后Activity 和Fragment 分别承担什么样的角色呢?
2.在RootView 里面有个很关键的成员变量,叫做mActive,在所有的View 上onAttachedToWindow 的时候让这个成员变量置为true ,在onDetachedFromWindow的时候将这个成员变量置为false,然后几乎在所有的Presenter的实现类里面做操作的时候,都会判断这个变量是否为true,是true 才进行操作,反之不进行操作.这样做让我感觉很奇怪,因为在RxPresenter里面不是detachView 的时候已经把所有的Observable都统一取消订阅了么?取消订阅之后就不会执行subscribe 后面的事情了吧?
3.在RollPagerView 和 SwipeDeck 都重写 了dispathTouchEvent的方法.在这里都getParent.requestDisallowInterceptTouchEvent(true),但是这个getParent  要getParent 到哪一个级别呢.经过调试,必须getParent 到某有一个层级才能彻底的处理滑动冲突.还望解答一下?

**Comment by caopeng000** [comment]
1.没有专门提供Model,是直接在Presenter 里面做的API 调用操作
如果按照正常的规范写法应该是专门创建一个管理数据的类，然后Presenter去调用它，但是目前Presenter涉及的数据操作不是很多，就是普通的加载第一页，第二页，所以就写在一起了。如果需要，可自行封装数据层。
2.mActive的作用？
由于网络请求是异步的，所以可能会碰到，请求没回来，但是界面就销毁了。此时如果不通过判断是否界面已经被销毁就会造成空指针异常或者内存泄露
